### ISSUE TITLE
Model Raycasting (by Ecu)

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#70]
I think that NOVA should have improved raycasting support for handling child detection for blocks, entities, etc. Perhaps via actually implementing a raycas

**Comment by anti344** [comment]
And to raycast tilted AABB's. And other basic shapes, not only the cubes.
And some kind of constructed colliders from this shapes

**Comment by calclavia** [comment]
@anti344 Raycast to Cuboid sounds good. :)

**Comment by Ecu** [comment]
Specifically what I wanted is the ability to find out what child of a model was hit by a ray cast if a model contains multiple children.  Ender Storage would need such feature in order to implement its color code frequency system.

It may be possible to accomplish the same thing already by doing the math yourself based on the position given with left/right clicks.  However, I think we'd benefit as an API to make it really easy to implement some form of child detection as part of the system itself.  Since this could be desired for custom hotkey features of a mod, a generic ray casting system that provides some form of list of 'hits' would probably be a good approach.

**Comment by anti344** [comment]
Yup, it would be cool.
But you dramatizing too much, once i did a similar to EnderStorage thing. AxisAlignedBB#intersects was pretty useful.
But again, an API to do this in a couple of lines would be nice, i agree.

**Comment by Ecu** [comment]
Oh, I know that it could definitely be implemented using what we have already (at least the changing color of nodes, as I don't believe you can override the selection cubes currently).  I just feel that a lot of NOVA mod developers will end up being NEW developers initially.  So being able to say it is super easy to do this kind of things will be a great way to get more people on board.

Not to mention, since this shouldn't be limited to blocks only (and should extend to entity models as well), it'd be a great way to implement things that let you click on specific parts of creatures or location-based damage without it being too daunting.

**Comment by anti344** [comment]
That's why i said about tilted BB's, so you could click very specifically on entities =P

**Comment by Ecu** [comment]
Missed that, sorry!

**Comment by calclavia** [comment]
Finished raycast for cuboids!
